version: '3.8'

services:
  telegram-bot:
    build: ./bot_telegram
    command: python bot_telegram/src/bot.py
    env_file:
      - .env
    restart: always

  fastapi-api:
    build: .
    command: uvicorn chat.chatbot:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: always